const products = [
  {
    id: 1,
    title: "Classic Cotton T-Shirt",
    price: 799,
    category: "Fashion",
    brand: "UrbanWear",
    description: "Soft cotton t-shirt perfect for daily wear.",
    rating: 4.2,
    discountPercentage: 10,
    image: "https://m.media-amazon.com/images/I/81CYs+7ggNL._AC_UY1100_.jpg",
  },

  {
    id: 2,
    title: "Men’s Running Sneakers",
    price: 2599,
    category: "Shoes",
    brand: "RunnerPro",
    description: "Comfortable sneakers built for running and training.",
    rating: 4.4,
    discountPercentage: 12,
    image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcS47k2almn-CExfa9EgJaLKlzc8euuQZFFaSQ5NUArqtXryWzxKdkWlF2fRC0qsTN1vaTfaRVkur72S9mDCTJdWmDGqEWPPUuwbh8iXszk3_2XzS10WyrPpxw",
  },

  {
    id: 3,
    title: "Wireless Bluetooth Headphones",
    price: 1899,
    category: "Electronics",
    brand: "SoundMax",
    description: "Wireless headphones delivering clear sound and bass.",
    rating: 4.3,
    discountPercentage: 15,
    image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSH-L1wptEWh_pqtT02_z_3VR0N31W7Glad3erC8ElPv9Jk9UI4AwmPRhZ_LEp5r6FJyR5BTiMTh9R5ZI7I9bHOegW8d_3PrpB27t8j8gOx",
  },

  {
    id: 4,
    title: "Women’s Western Top",
    price: 999,
    category: "Western Wear",
    brand: "StyleAura",
    description: "Trendy western top suitable for casual outings.",
    rating: 4.1,
    discountPercentage: 8,
    image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRxdj8HYrYayFhNEbu7POP7pTXZUqQ4yXfgzDVTGKSUzGCtLJLAndLdLdS_IBoS_0AGaODmDk_d78TdbrCucTLunzRcWUWY00L6ZWxvlOBj",
  },

  {
    id: 5,
    title: "Laptop Backpack",
    price: 1599,
    category: "Bags",
    brand: "CarryX",
    description: "Durable backpack designed with extra laptop padding.",
    rating: 4.4,
    discountPercentage: 20,
    image: "https://www.furjaden.com/cdn/shop/files/Features1copy.jpg?v=1704874951",
  },

  {
    id: 6,
    title: "Smart Digital Watch",
    price: 1699,
    category: "Accessories",
    brand: "TechTime",
    description: "Digital watch loaded with multiple smart features.",
    rating: 4.0,
    discountPercentage: 10,
    image: "https://www.jiomart.com/images/product/original/rvxxvvmuny/iloz-new-trendy-smart-looking-square-black-dial-led-digital-display-waterproof-pink-silicone-strap-kids-smart-sports-watches-watch-for-girl-s-product-images-rvxxvvmuny-3-202310272027.jpg?im=Resize=(500,630)",
  },

  {
    id: 7,
    title: "Women’s Handbag",
    price: 2199,
    category: "Fashion",
    brand: "Eleganza",
    description: "Elegant handbag crafted for everyday use.",
    rating: 4.3,
    discountPercentage: 18,
    image: "https://img.tatacliq.com/images/i25//437Wx649H/MP000000027133406_437Wx649H_202506280148452.jpeg",
  },

  {
    id: 8,
    title: "Smartphone Desk Stand",
    price: 599,
    category: "Gadgets",
    brand: "FlexiHold",
    description: "Adjustable stand ideal for watching videos.",
    rating: 4.2,
    discountPercentage: 6,
    image: "https://5.imimg.com/data5/SELLER/Default/2024/2/382463780/OI/ZA/JD/200324666/360-degree-rotating-mobile-stand-aluminum-desk-office-foldable-desktop-phone-holder-500x500.jpg",
  },

  {
    id: 9,
    title: "Hardcover Journal Notebook",
    price: 349,
    category: "Stationery",
    brand: "WritePro",
    description: "Premium quality notebook for writing and notes.",
    rating: 4.6,
    discountPercentage: 5,
    image: "https://images.meesho.com/images/products/454078566/s64ox_512.webp?width=512",
  },

  {
    id: 10,
    title: "Gaming RGB Mouse",
    price: 1299,
    category: "Electronics",
    brand: "ClickFire",
    description: "High precision mouse with RGB lighting.",
    rating: 4.7,
    discountPercentage: 14,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTM2CPkxCBikLjRBvoSQnnUV-o5ZdU29DGKBA&s",
  },

  {
    id: 11,
    title: "Sports Water Bottle",
    price: 499,
    category: "Sports",
    brand: "HydroFit",
    description: "Stainless-steel water bottle ideal for workouts.",
    rating: 4.5,
    discountPercentage: 10,
    image: "https://nestasia.in/cdn/shop/files/waterbottles_1.jpg?v=1697692790&width=600",
  },

  {
    id: 12,
    title: "LED Study Lamp",
    price: 699,
    category: "Home",
    brand: "BrightLite",
    description: "Compact desk lamp with adjustable brightness.",
    rating: 4.2,
    discountPercentage: 9,
    image: "https://offers.saventurebiz.com/wp-content/uploads/2023/11/table-lamp-01.jpg",
  },

  {
    id: 13,
    title: "Hooded Sweatshirt",
    price: 1299,
    category: "Fashion",
    brand: "UrbanWear",
    description: "Soft and warm hoodie for winter comfort.",
    rating: 4.3,
    discountPercentage: 11,
    image: "https://assets.ajio.com/medias/sys_master/root/20241006/70w1/6702a826260f9c41e85ba2e0/-473Wx593H-700540721-grey-MODEL.jpg",
  },

  {
    id: 14,
    title: "Women’s Sport Shoes",
    price: 1999,
    category: "Shoes",
    brand: "StridePlus",
    description: "Lightweight shoes ideal for walking and jogging.",
    rating: 4.4,
    discountPercentage: 16,
    image: "https://i5.walmartimages.com/asr/882b66c9-a99f-495b-af50-73e8e62982f8.100fc2cb9df8549435a9a7a50c9ddf10.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF",
  },

  {
    id: 15,
    title: "Portable Bluetooth Speaker",
    price: 1499,
    category: "Electronics",
    brand: "BeatBox",
    description: "Mini speaker with loud and clear sound output.",
    rating: 4.5,
    discountPercentage: 13,
    image: "https://static1.industrybuying.com/products/it-security/speaker-headphones/speakers/portable-bluetooth-speakers/ITS.POR.828202446_1734437377080.webp",
  },

  {
    id: 16,
    title: "Non-stick Kitchen Knife Set",
    price: 899,
    category: "Kitchen",
    brand: "ChefPro",
    description: "Sharp knife set suitable for daily chopping.",
    rating: 4.1,
    discountPercentage: 12,
    image: "https://m.media-amazon.com/images/I/91ozKGN5nmL._AC_UF894,1000_QL80_.jpg",
  },

  {
    id: 17,
    title: "Aromatic Candle Pack",
    price: 399,
    category: "Home",
    brand: "AromaLite",
    description: "Scented candles perfect for relaxation.",
    rating: 4.2,
    discountPercentage: 5,
    image: "https://jivisa.in/cdn/shop/files/JiVisa-Luxury-Soy-Wax-Candle-Gift-Box-JiViSa-689.jpg?v=1684806394",
  },

  {
    id: 18,
    title: "Wooden Wall Clock",
    price: 1199,
    category: "Home Decor",
    brand: "TimeCraft",
    description: "Designer wall clock with a premium finish.",
    rating: 4.3,
    discountPercentage: 10,
    image: "https://www.titan.co.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dw9e13249e/images/Titan/Catalog/W0098WA01_1.jpg?sw=600&sh=600",
  },

  {
    id: 19,
    title: "Study Table",
    price: 3499,
    category: "Furniture",
    brand: "FurniCraft",
    description: "Compact study table for home or office use.",
    rating: 4.4,
    discountPercentage: 18,
    image: "https://images-cdn.ubuy.co.in/656516d5333c862ba93f108c-qqxxwood-study-desk-with-chair-and.jpg",
  },

  {
    id: 20,
    title: "Office Chair",
    price: 4599,
    category: "Furniture",
    brand: "ChairMax",
    description: "Comfortable office chair with adjustable height.",
    rating: 4.5,
    discountPercentage: 20,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTniWiyySR2dV8h3qZPkuNBfsPpizcmbo_kfz4LZfW_oZN3t3WFgnpugQQsqyItwsvJKfo&usqp=CAU",
  },

  {
    id: 21,
    title: "Western Denim Jacket",
    price: 1899,
    category: "Western Wear",
    brand: "DenimHub",
    description: "Stylish denim jacket for a fashionable look.",
    rating: 4.3,
    discountPercentage: 12,
    image: "https://sko-uno.com/wp-content/uploads/2021/06/W4481514V_1.jpeg",
  },

  {
    id: 22,
    title: "Casual Slip-on Shoes",
    price: 1299,
    category: "Shoes",
    brand: "FootEase",
    description: "Comfortable slip-ons ideal for casual outings.",
    rating: 4.1,
    discountPercentage: 9,
    image: "https://hitz.co.in/cdn/shop/files/HITZ101-TAN-A.jpg?v=1755619411",
  },

  {
    id: 23,
    title: "Face Moisturizer Cream",
    price: 599,
    category: "Beauty",
    brand: "GlowCare",
    description: "Moisturizer that keeps skin soft and hydrated.",
    rating: 4.3,
    discountPercentage: 8,
    image: "https://m.media-amazon.com/images/I/61xPSdZ3WeL._AC_UF1000,1000_QL80_.jpg",
  },

  {
    id: 24,
    title: "Kids Cotton Shirt",
    price: 699,
    category: "Kids",
    brand: "MiniWorld",
    description: "Cute cotton shirt designed for kids.",
    rating: 4.5,
    discountPercentage: 5,
    image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQKqoXOi9pGagXRnZ-pNTRcgzClzFznyupJiRrQMb1EYKoIa3qycNfy8nPEsXq4xW3ZmabaUmZf4rcj6lvEqVDQFyGq2rMO8U-DQAuYtSKQIqL1LZs0tVBzow",
  },

  {
    id: 25,
    title: "c",
    price: 999,
    category: "Fashion",
    brand: "Ethniq",
    description: "Beautiful kurti suitable for festive occasions.",
    rating: 4.6,
    discountPercentage: 10,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS88M4EQkQ9B3C7zZCAOs9JVjoKrrdJyBvx0Q&s",
  },

  {
    id: 26,
    title: "Wireless Keyboard",
    price: 1299,
    category: "Electronics",
    brand: "TechKeys",
    description: "Compact wireless keyboard with smooth keys.",
    rating: 4.2,
    discountPercentage: 11,
    image: "https://images-cdn.ubuy.co.in/6842043fbdb0067ec00db984-magegee-portable-60-mechanical-gaming.jpg",
  },

  {
    id: 27,
    title: "Sports Gym T-Shirt",
    price: 799,
    category: "Sports",
    brand: "FitPlus",
    description: "Breathable gym t-shirt designed for workouts.",
    rating: 4.4,
    discountPercentage: 10,
    image: "https://5.imimg.com/data5/MH/FQ/FU/SELLER-11145209/mens-gym-polyester-lycra-t-shirt.jpg",
  },

  {
    id: 28,
    title: "Hair Dryer 2000W",
    price: 1499,
    category: "Beauty",
    brand: "HairPro",
    description: "Powerful hair dryer delivering fast drying.",
    rating: 4.3,
    discountPercentage: 13,
    image: "https://www.enzoita.com/uploads/202340061/2000w-blow-dryer7e526a0b-372b-482d-bcf4-83baa345af2c.jpg",
  },

  {
    id: 29,
    title: "Designer Bedsheet",
    price: 899,
    category: "Home",
    brand: "ComfortSoft",
    description: "Soft cotton bedsheet with premium prints.",
    rating: 4.2,
    discountPercentage: 6,
    image: "https://www.textileinfomedia.com/img/booi/designer-embroidered-bed-sheet-full.jpg",
  },

  {
    id: 30,
    title: "Casual Men’s Shirt",
    price: 1299,
    category: "Fashion",
    brand: "UrbanWear",
    description: "Patterned shirt made for casual outings.",
    rating: 4.3,
    discountPercentage: 9,
    image: "https://campussutra.com/cdn/shop/files/CSMOVSRT7609_3_52eadbc3-3c06-4480-abda-47bf3a54c0dd.jpg?v=1730801146&width=2000",
  },

  {
    id: 31,
    title: "Bluetooth Earbuds",
    price: 1699,
    category: "Electronics",
    brand: "SoundMax",
    description: "Mini earbuds with clear audio output.",
    rating: 4.4,
    discountPercentage: 16,
    image: "https://rukminim2.flixcart.com/image/480/640/xif0q/headphone/d/f/4/latest-bluetooth-earbuds-2024-new-tws-wireless-headphones-5-0-original-imahfynqb7rhezad.jpeg?q=90",
  },

  {
    id: 32,
    title: "Women’s Palazzo Pants",
    price: 899,
    category: "Fashion",
    brand: "TrendPlus",
    description: "Comfort-fit palazzo pants for all-day wear.",
    rating: 4.2,
    discountPercentage: 7,
    image: "https://assets.ajio.com/medias/sys_master/root/20230704/aV1i/64a43001a9b42d15c9342dcd/-473Wx593H-442087660-ecru-MODEL.jpg",
  },

  {
    id: 33,
    title: "Men’s Formal Shoes",
    price: 2499,
    category: "Shoes",
    brand: "RoyalStep",
    description: "Classic formal shoes crafted in premium material.",
    rating: 4.4,
    discountPercentage: 12,
    image: "https://kxadmin.metroshoes.com/product/19-6040-11-40/1200/19-6040H11.jpg",
  },

  {
    id: 34,
    title: "Kitchen Blender",
    price: 2199,
    category: "Kitchen",
    brand: "BlendPro",
    description: "Efficient blender ideal for shakes and chutneys.",
    rating: 4.3,
    discountPercentage: 15,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvgCIZ6RvUUfbeVtWmJTKWDwTesPIfQFmPeA&s",
  },

  {
    id: 35,
    title: "Cushioned Office Stool",
    price: 1399,
    category: "Furniture",
    brand: "FurniCraft",
    description: "Compact stool great for office and home.",
    rating: 4.0,
    discountPercentage: 10,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTODPXD69TCDJ69Xkyqbr3y6TiMJbZKBQOmRQ&s",
  },

  {
    id: 36,
    title: "Women’s Maxi Dress",
    price: 1699,
    category: "Western Wear",
    brand: "DressMe",
    description: "Elegant long dress with a flowy design.",
    rating: 4.5,
    discountPercentage: 18,
    image: "https://raassio.com/cdn/shop/files/44A2604-2.jpg?v=1707370324&width=1946",
  },

  {
    id: 37,
    title: "Running Shorts",
    price: 699,
    category: "Sports",
    brand: "FitPlus",
    description: "Lightweight shorts designed for running.",
    rating: 4.2,
    discountPercentage: 7,
    image: "https://contents.mediadecathlon.com/p2841949/894eb6ff5bcb1770d08d8d89b15ac6f5/p2841949.jpg",
  },

  {
    id: 38,
    title: "Women’s Sandals",
    price: 1299,
    category: "Shoes",
    brand: "ComfortStep",
    description: "Comfortable sandals with soft cushioning.",
    rating: 4.3,
    discountPercentage: 12,
    image: "https://images-static.nykaa.com/media/catalog/product/7/6/7682375EL-AAA-Wn-102White_1.jpg?tr=w-500",
  },

  {
    id: 39,
    title: "Kids Toy Car",
    price: 599,
    category: "Kids",
    brand: "ToyJoy",
    description: "Colorful toy car built for kids’ fun.",
    rating: 4.3,
    discountPercentage: 8,
    image: "https://www.patoys.in/cdn/shop/files/patoys-kids-electric-toy-big-size-benz-vintage-car-with-remote-control-636855.jpg?v=1742744611&width=1946",
  },

  {
    id: 40,
    title: "Beard Trimmer",
    price: 1199,
    category: "Beauty",
    brand: "TrimPro",
    description: "Rechargeable beard trimmer with sharp blades.",
    rating: 4.4,
    discountPercentage: 11,
    image: "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Small%20Appliances/Grooming/Images/306500_sv2s3r.png",
  },

  {
    id: 41,
    title: "Cotton Bedsheet",
    price: 899,
    category: "Home",
    brand: "SleepWell",
    description: "Soft cotton bedsheet with a smooth finish.",
    rating: 4.4,
    discountPercentage: 5,
    image: "https://www.malako-india.com/cdn/shop/products/malako-royale-xl-yellow-botanic-king-size-100-cotton-bedsheetbedding-set-998419.jpg?v=1754834558",
  },

  {
    id: 42,
    title: "Designer Wrist Watch",
    price: 1999,
    category: "Accessories",
    brand: "TimePro",
    description: "Stylish analog watch for a classy look.",
    rating: 4.3,
    discountPercentage: 15,
    image: "https://images-cdn.ubuy.co.in/65c7eb4bc9e49b181137e0dc-poedagar-top-brand-luxury-men-watch.jpg",
  },

  {
    id: 43,
    title: "JBL Style Speaker",
    price: 2199,
    category: "Electronics",
    brand: "BeatRox",
    description: "Portable Bluetooth speaker with punchy bass.",
    rating: 4.5,
    discountPercentage: 19,
    image: "https://www.dealsplant.com/cdn/shop/files/8158qIaeANL._SX569_1024x.jpg?v=1717167860",
  },

  {
    id: 44,
    title: "Printed Women’s Kurti",
    price: 1199,
    category: "Fashion",
    brand: "Ethniq",
    description: "Printed kurti suited for casual wear.",
    rating: 4.2,
    discountPercentage: 8,
    image: "https://www.mustardfashion.com/wp-content/uploads/2024/10/T1101-4.jpg",
  },

  {
    id: 45,
    title: "Men’s Sports Track Pants",
    price: 899,
    category: "Sports",
    brand: "FitPlus",
    description: "Flexible track pants perfect for gym and jogging.",
    rating: 4.2,
    discountPercentage: 10,
    image: "https://assets.myntassets.com/dpr_1.5,q_30,w_400,c_limit,fl_progressive/assets/images/33801826/2025/5/5/a67c532b-b4e6-46db-a5d2-5b31b86eb98e1746446462233-HRX-by-Hrithik-Roshan-Men-Track-Pants-861746446461441-1.jpg",
  },

  {
    id: 46,
    title: "Women’s Heels",
    price: 1999,
    category: "Shoes",
    brand: "GlamStep",
    description: "Stylish heels suitable for parties.",
    rating: 4.4,
    discountPercentage: 16,
    image: "https://imagescdn.vanheusenindia.com/img/app/product/9/940361-12028056.jpg?auto=format&w=390",
  },

  {
    id: 47,
    title: "Makeup Brush Set",
    price: 799,
    category: "Beauty",
    brand: "BeautyBox",
    description: "Soft and durable brushes for smooth makeup.",
    rating: 4.3,
    discountPercentage: 12,
    image: "https://assets.myntassets.com/w_412,q_auto:best,dpr_3,fl_progressive,f_webp/assets/images/24035472/2023/7/27/fba049f6-918b-432d-9d4c-5930774076a71690454063863-Renee-Set-Of-6-All-In-1-Professional-Makeup-Brushes-32116904-1.jpg",
  },

  {
    id: 48,
    title: "Kitchen Mixer Grinder",
    price: 2899,
    category: "Kitchen",
    brand: "KitchenMax",
    description: "Efficient mixer grinder for home kitchens.",
    rating: 4.5,
    discountPercentage: 18,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0ONakweqroDyx8l94cRkHakVSd80QY5t5EQ&s",
  },

  {
    id: 49,
    title: "Modern Sofa Cushion",
    price: 699,
    category: "Home Decor",
    brand: "SoftNest",
    description: "Comfortable cushion enhancing sofa looks.",
    rating: 4.1,
    discountPercentage: 6,
    image: "https://www.urbanspacestore.in/cdn/shop/products/bohoorangecushion3front.jpg?v=1757569571",
  },

  {
    id: 50,
    title: "Sports Smartwatch",
    price: 2499,
    category: "Electronics",
    brand: "TechTime",
    description: "Smartwatch with fitness features and notifications.",
    rating: 4.4,
    discountPercentage: 15,
    image: "https://www.verywellfit.com/thmb/bpALJ4kWfuNKmoqItOn8sjMjNLI=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Web_1500-vwt-polar-vantage-christine-luff-10-225eebe0e8784d86bc9d093da806e168.jpg",
  },

  {
    id: 51,
    title: "Kids Pencil Box",
    price: 299,
    category: "Stationery",
    brand: "WritePro",
    description: "Cute pencil box ideal for school children.",
    rating: 4.5,
    discountPercentage: 5,
    image: "https://www.jiomart.com/images/product/original/rv0wfzj19q/medica-pencil-box-for-kids-0a11-product-images-orv0wfzj19q-p608161828-0-202402241449.jpg?im=Resize=(420,420)",
  },

  {
    id: 52,
    title: "Synthetic Leather Belt",
    price: 699,
    category: "Accessories",
    brand: "BeltCraft",
    description: "Durable leather belt with a stylish buckle.",
    rating: 4.3,
    discountPercentage: 10,
    image: "https://kosherleather.in/cdn/shop/files/97DZo5se.jpg?v=1752602467",
  },

  {
    id: 53,
    title: "Glass Water Jug",
    price: 699,
    category: "Kitchen",
    brand: "HomeServe",
    description: "Transparent water jug perfect for dining tables.",
    rating: 4.2,
    discountPercentage: 8,
    image: "https://m.media-amazon.com/images/I/413i9GzhmRL._AC_UF894,1000_QL80_.jpg",
  },

  {
    id: 54,
    title: "Wooden Flower Vase",
    price: 999,
    category: "Home Decor",
    brand: "DecoCraft",
    description: "Handcrafted vase perfect for living rooms.",
    rating: 4.4,
    discountPercentage: 12,
    image: "https://i.etsystatic.com/6202975/r/il/c50cc7/1104459102/il_1080xN.1104459102_5xvc.jpg",
  },

  {
    id: 55,
    title: "Women's Stylish Jeans",
    price: 1799,
    category: "Western Wear",
    brand: "DenimHub",
    description: "High-quality denim jeans with perfect fit.",
    rating: 4.5,
    discountPercentage: 18,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKITx0bx8ex--nTBgX2NH8SMkAOawcMLmXAg&s",
  },

  {
    id: 56,
    title: "Men’s Casual Sneakers",
    price: 1899,
    category: "Shoes",
    brand: "FootEase",
    description: "Comfortable sneakers suitable for daily use.",
    rating: 4.3,
    discountPercentage: 15,
    image: "https://huckberry.imgix.net/pages/081325-fallsneakershopupdate-5-jpg-4ee03d4f24.jpg?auto=format%2C%20compress&crop=top&fit=clip&cs=tinysrgb&ixlib=react-9.8.1",
  },

  {
    id: 57,
    title: "Wireless Charging Pad",
    price: 899,
    category: "Gadgets",
    brand: "VoltCharge",
    description: "Fast wireless charging pad for smartphones.",
    rating: 4.2,
    discountPercentage: 11,
    image: "https://picsum.photos/id/520/600/600",
  },

  {
    id: 58,
    title: "Women’s Ethnic Dupatta",
    price: 699,
    category: "Fashion",
    brand: "Ethniq",
    description: "Elegant dupatta designed for festive wear.",
    rating: 4.3,
    discountPercentage: 10,
    image: "https://picsum.photos/id/1018/600/600",
  },

  {
    id: 59,
    title: "Mattress Protector",
    price: 1199,
    category: "Home",
    brand: "SleepWell",
    description: "Waterproof protector suitable for beds.",
    rating: 4.2,
    discountPercentage: 6,
    image: "https://picsum.photos/id/545/600/600",
  },

  {
    id: 60,
    title: "Hair Straightener",
    price: 1699,
    category: "Beauty",
    brand: "HairPro",
    description: "Easy-to-use straightener for smooth hair.",
    rating: 4.4,
    discountPercentage: 14,
    image: "https://picsum.photos/id/456/600/600",
  },

  {
    id: 61,
    title: "Men’s Formal Shirt",
    price: 1499,
    category: "Fashion",
    brand: "UrbanWear",
    description: "Premium shirt ideal for formal events.",
    rating: 4.3,
    discountPercentage: 10,
    image: "https://picsum.photos/id/1025/600/600",
  },

  {
    id: 62,
    title: "Women’s Flats",
    price: 999,
    category: "Shoes",
    brand: "StepSoft",
    description: "Comfortable flats for daily use.",
    rating: 4.1,
    discountPercentage: 8,
    image: "https://picsum.photos/id/232/600/600",
  },

  {
    id: 63,
    title: "Kitchen Chopping Board",
    price: 499,
    category: "Kitchen",
    brand: "ChefPro",
    description: "Durable chopping board made from high-quality wood.",
    rating: 4.2,
    discountPercentage: 7,
    image: "https://picsum.photos/id/241/600/600",
  },

  {
    id: 64,
    title: "Soft Bath Towel",
    price: 699,
    category: "Home",
    brand: "ComfortSoft",
    description: "Highly absorbent towel made from premium cotton.",
    rating: 4.3,
    discountPercentage: 9,
    image: "https://picsum.photos/id/280/600/600",
  },

  {
    id: 65,
    title: "Women’s Party Dress",
    price: 2999,
    category: "Western Wear",
    brand: "StyleAura",
    description: "Elegant dress perfect for evening parties.",
    rating: 4.5,
    discountPercentage: 20,
    image: "https://picsum.photos/id/1030/600/600",
  },

  {
    id: 66,
    title: "Office Laptop Stand",
    price: 1399,
    category: "Gadgets",
    brand: "FlexiHold",
    description: "Adjustable laptop stand ideal for office setups.",
    rating: 4.4,
    discountPercentage: 14,
    image: "https://picsum.photos/id/530/600/600",
  },

  {
    id: 67,
    title: "Kids School Backpack",
    price: 999,
    category: "Kids",
    brand: "MiniWorld",
    description: "Lightweight backpack designed for children.",
    rating: 4.3,
    discountPercentage: 7,
    image: "https://picsum.photos/id/889/600/600",
  },

  {
    id: 68,
    title: "Women’s Earrings",
    price: 599,
    category: "Accessories",
    brand: "ShineAura",
    description: "Stylish earrings suitable for any outfit.",
    rating: 4.4,
    discountPercentage: 10,
    image: "https://picsum.photos/id/232/600/600",
  },

  {
    id: 69,
    title: "USB Desk Fan",
    price: 799,
    category: "Gadgets",
    brand: "CoolTech",
    description: "Portable USB fan perfect for office use.",
    rating: 4.2,
    discountPercentage: 6,
    image: "https://picsum.photos/id/180/600/600",
  },

  {
    id: 70,
    title: "Men’s Wallet",
    price: 999,
    category: "Accessories",
    brand: "WalletCraft",
    description: "Slim and sturdy wallet with multiple pockets.",
    rating: 4.3,
    discountPercentage: 11,
    image: "https://picsum.photos/id/433/600/600",
  },

  {
    id: 71,
    title: "Kitchen Spice Rack",
    price: 1299,
    category: "Kitchen",
    brand: "HomeServe",
    description: "Multi-container spice rack perfect for kitchens.",
    rating: 4.2,
    discountPercentage: 13,
    image: "https://picsum.photos/id/250/600/600",
  },

  {
    id: 72,
    title: "Women’s Leggings",
    price: 699,
    category: "Fashion",
    brand: "TrendPlus",
    description: "Comfort-fit leggings suitable for casual wear.",
    rating: 4.1,
    discountPercentage: 6,
    image: "https://picsum.photos/id/1013/600/600",
  },

  {
    id: 73,
    title: "Smart Fitness Band",
    price: 1499,
    category: "Electronics",
    brand: "FitTrack",
    description: "Fitness band that tracks steps and heart rate.",
    rating: 4.3,
    discountPercentage: 15,
    image: "https://picsum.photos/id/1076/600/600",
  },

  {
    id: 74,
    title: "Boys Sports Shoes",
    price: 1399,
    category: "Kids",
    brand: "MiniWorld",
    description: "Lightweight and comfortable shoes for kids.",
    rating: 4.2,
    discountPercentage: 10,
    image: "https://picsum.photos/id/215/600/600",
  },

  {
    id: 75,
    title: "Makeup Compact Powder",
    price: 799,
    category: "Beauty",
    brand: "GlowCare",
    description: "Compact powder giving smooth matte finish.",
    rating: 4.3,
    discountPercentage: 9,
    image: "https://picsum.photos/id/823/600/600",
  },
];

module.exports = {
    products
}